require 'open-uri'

User.destroy_all

demo = User.create({ fname: "Demo", lname: "Demonstration", age: 18, email: "demo@mail.com", password: "password" })
sample = User.create({ fname: "Sample", lname: "Sampleton", age: 18, email: "sample@mail.com", password: "password" })

Photo.destroy_all

photo1 = Photo.create({ user_id: demo.id, title: "Elephant in the room", description: "Elephant highlighted by break in the canopy, this is the closest I've ever been to one!" })
photo2 = Photo.create({ user_id: sample.id, title: "Long exposure stream", description: "Long exposure shot of a soft stream, amazing how fast snowy mountains can transition into tree filled greenery" })
photo3 = Photo.create({ user_id: demo.id, title: "Clear Valley", description: "Yosemite Valley on a calm summer day" })
photo4 = Photo.create({ user_id: demo.id, title: "Light and lightning", description: "Cool light bar picture perfectly timed with lightning in background" })
photo5 = Photo.create({ user_id: demo.id, title: "Ghosts", description: "Incredible line up of Koenigseggs during the annual meetup of the Ghost Squadron" })
photo6 = Photo.create({ user_id: sample.id, title: "Big air", description: "Amazing air caught by this rally car over a hill" })
photo7 = Photo.create({ user_id: sample.id, title: "Old faithful eruption", description: "Old faithful in the light of the beautiful Yellowstone sunset" })
photo8 = Photo.create({ user_id: demo.id, title: "Taking flight", description: "Low clearance at a very high speed over a mountain side, adrenaline must be pumping!" })
photo9 = Photo.create({ user_id: sample.id, title: "Knee drags", description: "The greater the lean, the faster the turn, expalins why the leader is knee dragging!" })
photo10 = Photo.create({ user_id: demo.id, title: "Tetons from Jenny Lake", description: "View of the Tetons from over the glistening Jenny Lake" })
photo11 = Photo.create({ user_id: demo.id, title: "What a Grand Canyon", description: "I can't believe somebody has jumped this enormous crevasse in the ground on a motor bike! What a view!" })
photo12 = Photo.create({ user_id: sample.id, title: "Must be a big horse", description: "The wonders that water can create! Simply stunning." })
photo13 = Photo.create({ user_id: sample.id, title: "Jeep being a Jeep", description: "Here we see a wild jeep in its natural habitat, don't spook it!" })
photo14 = Photo.create({ user_id: sample.id, title: "Air Hug!", description: "It's incredible to see what creations humans have come up with. The amount of technological advancement here is amazing!" })
photo15 = Photo.create({ user_id: sample.id, title: "King of the Jungle", description: "An apex predator at rest." })
photo16 = Photo.create({ user_id: demo.id, title: "Wonder of the new world", description: "Undiscovered by the Spanish, these Incan ruins remain in tact, resting on the Andean mountain range." })
photo17 = Photo.create({ user_id: sample.id, title: "I can fly!", description: "The stunts that these athletes learn to become comfortable with I will never understand." })
photo18 = Photo.create({ user_id: sample.id, title: "Squad", description: "Nothing is a better time than some time on the mountain with a great group of friends!" })
photo19 = Photo.create({ user_id: demo.id, title: "Colorful Sky", description: "Once in a blue moon sunset! So lucky to have been here when it happened." })
photo20 = Photo.create({ user_id: sample.id, title: "Deadly waves", description: "One of the most dangerous surfing destinations on the planet. The water was incredibly forceful but these waves are unlike anywhere else on the globe." })
photo21 = Photo.create({ user_id: demo.id, title: "Window to the universe", description: "Clear night skies so I had to get my camera out, got some great shots!" })
photo22 = Photo.create({ user_id: sample.id, title: "Macro Practice", description: "Found a little bee subject to practice some macro photography on." })
photo23 = Photo.create({ user_id: sample.id, title: "Aggressive purple", description: "test1" })
photo24 = Photo.create({ user_id: demo.id, title: "title1", description: "test2" })
photo25 = Photo.create({ user_id: demo.id, title: "title2", description: "test3" })
photo26 = Photo.create({ user_id: demo.id, title: "title3", description: "test4" })
photo27 = Photo.create({ user_id: sample.id, title: "title4", description: "test5" })
photo28 = Photo.create({ user_id: sample.id, title: "title5", description: "test6" })
photo29 = Photo.create({ user_id: sample.id, title: "title6", description: "test7" })
photo30 = Photo.create({ user_id: demo.id, title: "title7", description: "test8" })
photo31 = Photo.create({ user_id: demo.id, title: "title8", description: "test9" })
photo32 = Photo.create({ user_id: sample.id, title: "title9", description: "test10" })
photo33 = Photo.create({ user_id: sample.id, title: "title10", description: "test11" })
photo34 = Photo.create({ user_id: demo.id, title: "title11", description: "test12" })
photo35 = Photo.create({ user_id: demo.id, title: "title12", description: "test13" })
photo36 = Photo.create({ user_id: demo.id, title: "title13", description: "test14" })
photo37 = Photo.create({ user_id: sample.id, title: "title14", description: "test15" })
photo38 = Photo.create({ user_id: sample.id, title: "title15", description: "test16" })
photo39 = Photo.create({ user_id: sample.id, title: "title16", description: "test17" })
photo40 = Photo.create({ user_id: demo.id, title: "title17", description: "test18" })
photo41 = Photo.create({ user_id: demo.id, title: "title18", description: "test19" })
photo42 = Photo.create({ user_id: sample.id, title: "title19", description: "test20" })
photo43 = Photo.create({ user_id: sample.id, title: "title20", description: "test21" })
photo44 = Photo.create({ user_id: sample.id, title: "title21", description: "test22" })
photo45 = Photo.create({ user_id: demo.id, title: "title22", description: "test23" })
photo46 = Photo.create({ user_id: sample.id, title: "title23", description: "test24" })
photo47 = Photo.create({ user_id: demo.id, title: "title24", description: "test25" })
photo48 = Photo.create({ user_id: sample.id, title: "title25", description: "test26" })

photo1.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/elephant-1.jpg"), filename: "elephant-1.jpg")
photo2.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/nature-1.jpg"), filename: "nature-1.jpg")
photo3.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/yosemite-valley.jpg"), filename: "yosemite-valley.jpg")
photo4.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/light-painting-1.jpg"), filename: "light-painting-1.jpg")
photo5.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/ghost-squadron.jpg"), filename: "ghost-squadron.jpg")
photo6.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/rally-car.jpg"), filename: "rally-car.jpg")
photo7.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/old-faithful.jpg"), filename: "old-faithful.jpg")
photo8.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/wingsuit.jpg"), filename: "wingsuit.jpg")
photo9.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/motogp.jpg"), filename: "motogp.jpg")
photo10.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/jenny-lake.jpg"), filename: "jenny-lake.jpg")
photo11.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/grand-canyon-1.jpg"), filename: "grand-canyon-1.jpg")
photo12.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/horseshoe-bend-1.jpg"), filename: "horseshoe-bend-1.jpg")
photo13.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/jeep-rocks.jpg"), filename: "jeep-rocks.jpg")
photo14.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/jet-hug.jpg"), filename: "jet-hug.jpg")
photo15.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/lion-1.jpg"), filename: "lion-1.jpg")
photo16.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/machu-picchu-1.jpg"), filename: "machu-picchu-1.jpg")
photo17.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/motocross-jump.jpg"), filename: "motocross-jump.jpg")
photo18.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/snowboard-squad.jpg"), filename: "snowboard-squad.jpg")
photo19.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/sunset-1.jpg"), filename: "sunset-1.jpg")
photo20.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/cyclops-surfing.jpg"), filename: "cyclops-surfing.jpg")
photo21.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/astrophotography.jpg"), filename: "astrophotography.jpg")
photo22.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/bee-macro.jpg"), filename: "bee-macro.jpg")
photo23.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/brz.jpg"), filename: "brz.jpg")
photo24.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/cenote-2.jpg"), filename: "cenote-2.jpg")
photo25.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/cenote.jpg"), filename: "cenote.jpg")
photo26.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/climbing-bali.jpg"), filename: "climbing-bali.jpg")
photo27.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/desert-road-2.jpg"), filename: "desert-road-2.jpg")
photo28.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/desert-road.jpg"), filename: "desert-road.jpg")
photo29.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/eye-macro.jpg"), filename: "eye-macro.jpg")
photo30.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/f1.jpg"), filename: "f1.jpg")
photo31.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/half-dome.jpg"), filename: "half-dome.jpg")
photo32.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/koenigsegg.jpg"), filename: "koenigsegg.jpg")
photo33.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/lake-tahoe-sky.jpg"), filename: "lake-tahoe-sky.jpg")
photo34.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/lake-tahoe.jpg"), filename: "lake-tahoe.jpg")
photo35.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/landscape.jpg"), filename: "landscape.jpg")
photo36.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/leaves.jpg"), filename: "leaves.jpg")
photo37.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/waterfall.jpg"), filename: "waterfall.jpg")
photo38.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/moss.jpg"), filename: "moss.jpg")
photo39.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/night-landscape.jpg"), filename: "night-landscape.jpg")
photo40.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/skateboarder.jpg"), filename: "skateboarder.jpg")
photo41.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/skiing.jpg"), filename: "skiing.jpg")
photo42.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/snowboarding-2.jpg"), filename: "snowboarding-2.jpg")
photo43.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/spider-macro.jpg"), filename: "spider-macro.jpg")
photo44.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/surfing-2.jpg"), filename: "surfing-2.jpg")
photo45.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/surfing.jpg"), filename: "surfing.jpg")
photo46.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/tiger.jpg"), filename: "tiger.jpg")
photo47.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/waterfall-2.jpg"), filename: "waterfall-2.jpg")
photo48.image.attach(io: File.open("/Users/italo/Desktop/Full Stack/CamClickr/app/assets/images/waterfall-3.jpg"), filename: "waterfall-3.jpg")

# Album.destroy_all

# Album.create