import React from 'react';

class Greeting extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        const greetings = [
            "nǐ hǎo",
            "hola",
            "hello",
            "namaste",
            "marhabaan",
            "olá, oi, alô",
            "hyālō",
            "privet",
            "kon’nichiwa",
            "sata srī akāla",
            "hallo, guten tag",
            "nggoleki",
            "nóng hō",
            "selamat siang",
            "annyeong haseyo",
            "halō, vandanalu",
            "xin chào",
            "bonjour",
            "hĕlō, namaskār",
            "vaṇakkam",
            "assalam u alaikum",
            "salām",
            "merhaba",
            "nǐ hǎo",
            "ciao",
            "sà - wàt - dii",
            "namaste",
            "kaixo",
            "lı́ hó",
            "cześć’",
            "salam",
            "namaskāra",
            "halēā",
            "sampurasun",
            "hafa adai",
            "sannu",
            "min - ga - la - ba",
            "namaskar",
            "barev",
            "dobryj den",
            "prannam",
            "kamusta",
            "e nle o",
            "prannam",
            "assalam o alaikum",
            "habari",
            "salom",
            "selam",
            "mihofnima",
            "kedu",
            "akkam",
            "bună",
            "salam",
            "khurumjari",
            "vanakkam",
            "kumusta",
            "hallo",
            "slaw",
            "zdravo",
            "salama",
            "namaste",
            "tudha kaya haal hai saine",
            "henda ho",
            "choum reap sor",
            "ayubowan",
            "i ni ce",
            "namaskhar",
            "selamat pagi",
            "salaam alaykum",
            "subh pyaar",
            "ke aal aee",
            "khammaghani",
            "szia",
            "moni",
            "yasou",
            "wo ho te sεn ?",
            "kumno",
            "sälem",
            "dumela rra/mama",
            "shalom",
            "sawubona",
            "ahoj",
            "muraho",
            "deu boro dis dium",
            "bhala ni ?",
            "bonjou",
            "goeie dag",
            "nü hou",
            "naimbag nga aldaw",
            "allianchu",
            "bite",
            "hej",
            "nyob zoo",
            "mhoro",
            "hello",
            "yaxshimusiz",
            "chone tao ?",
            "dobry dzień",
            "ne y windiga",
            "mholweni"
        ];
        const languages = [
            "Mandarin",
            "Spanish",
            "English",
            "Hindi",
            "Arabic",
            "Portuguese",
            "Bengali",
            "Russian",
            "Japanese",
            "Punjabi",
            "German",
            "Javanese",
            "Wu(Shanghainese)",
            "Malay(Indonesian)",
            "Korean",
            "Telegu",
            "Vietnamese",
            "French",
            "Marathi",
            "Tamil",
            "Urdu",
            "Persian(Farsi)",
            "Turkish",
            "Cantonese",
            "Italian",
            "Thai",
            "Gujarati",
            "Basque",
            "Minnan",
            "Polish",
            "Pashto",
            "Kannada",
            "Malayalam",
            "Sundanese",
            "Chamorro",
            "Hausa",
            "Burmese",
            "Oriya",
            "Armenian",
            "Ukranian",
            "Bhojpuri",
            "Tagalog",
            "Yoruba",
            "Maithili",
            "Sindhi",
            "Swahili",
            "Uzbek",
            "Amharic",
            "Fula",
            "Igbo",
            "Oromo",
            "Romanian",
            "Azerbaijani",
            "Manipuri / Meitei",
            "Awadi",
            "Cebuano",
            "Dutch",
            "Kurdish",
            "Serbo - Croatian",
            "Malagasy",
            "Nepali",
            "Saraiki",
            "Santali",
            "Khmer",
            "Sinhalese",
            "Bambara",
            "Assamese",
            "Madurese",
            "Somali",
            "Magahi",
            "Dogri",
            "Marwari",
            "Hungarian",
            "Chewa",
            "Greek",
            "Akan / Twi",
            "Khasi",
            "Kazakh",
            "Tswana",
            "Hebrew",
            "Zulu",
            "Czech",
            "Kinyarwanda",
            "Konkani",
            "Sylheti",
            "Haitian Creole",
            "Afrikaans",
            "Min Dong",
            "Ilokano",
            "Quechua",
            "Kirundi",
            "Swedish",
            "Hmong",
            "Shona",
            "Hiligaynon",
            "Uyghur",
            "Balochi",
            "Belarusian",
            "Mossi",
            "Xhosa"
        ];
        const randNum = Math.floor(Math.random() * greetings.length);

        return (
            <div className="greeting">
                <h4>{greetings[randNum]}, {this.props.name}!</h4>
                <p>Now you know how to greet people in {languages[randNum]}</p>
            </div>
        )
    }
}

export default Greeting;